### PR TITLE
Submission ML-1

### PR DESCRIPTION
**Pull request by PriyanshuPansari**

### CODE REVIEW

**Comment by divo12** [comment]
@PriyanshuPansari cool stuff and well done for the brownie point problem 
But I couldn't access your kaggle notebook. Make sure you have given a public link

**Comment by PriyanshuPansari** [comment]
@divo12 I made the Kaggle notebook public and updated the link.
@DevPranjal I deleted the unrequired files, and about the messiness of the PR Is there a way to clean this pr now?

**Comment by divo12** [comment]
@PriyanshuPansari we can close this PR and you can put another PR by creating a branch like pranjal said

**Comment by PriyanshuPansari** [comment]
@divo12 I tried doing that but it was still showing history, that's why I closed that PR.

**Comment by divo12** [comment]
We'll close this PR. Then you'll be able to do from that side
Also your task 2 link and task 1 links are same

**Comment by divo12** [comment]
The Assignment looks fine to me
@DevPranjal have a skim through of the assignment and if it's fine we'll merge
@PriyanshuPansari next time make another branch for your assignment submission

**Pull request merged**
