### PR TITLE
ML-project Final Draft + DL-1 Assignment First Draft

### PR DESCRIPTION
**Pull request by guptaaryan16**
I am getting an accuracy score of only 49 percent after everything on Random Forest Classifier. Want to know what can I do to improve this accuracy.

### CODE REVIEW

**Comment by mr-sarthakgupta** [comment]
For DL-1, please get the test and train accuracy for each epoch. Also please consider training for more number of epochs.

**Comment by divo12** [comment]
ML project is fine
@mr-sarthakgupta you can merge the PR if the DL part is fine

**Comment by guptaaryan16** [comment]
Hey I am trying to work on the DL part to implement tensor board and suggestions by @mr-sarthakgupta, so can you merge it tomorrow

**Comment by guptaaryan16** [comment]
I have implemented Tensorboard and other changes, @mr-sarthakgupta  please review

**Comment by mr-sarthakgupta** [comment]
Seems good now.

**Pull request merged**
