### PR TITLE
Submits Assignment 1 (Sanidhya)

### PR DESCRIPTION
**Pull request by sanidhyas3s**
Ques 1 : L1-Assignment-(ML-0)/Ques1-Assignment1-dsg.txt
Ques 2 : L1-Assignment-(ML-0)/Ques2-Assignment1-dsg.ipynb

### CODE REVIEW

**Comment by DevPranjal** [comment]
Thanks for the quick submission.

Please follow the format mentioned in the assignment.
- Create a folder `ML-0-Submissions` inside the folder `ML`
- Submit a _single_ Jupyter Notebook named: `your-name.ipynb`
- Use Markdown cells within the Notebook for answering all the questions. You can read more about Markdown cells [here](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html)
- Also, answer the third question

**Comment by sanidhyas3s** [comment]
Okay, will update with the required changes and additions soon.

**Comment by sanidhyas3s** [comment]
@DevPranjal I have made the needed changes and wrote an answer to the third question, please check if anything else needs to be done.

**Comment by DevPranjal** [comment]
Thanks for the submission. It looks much better now.

Just a minor thing, could you please remove the folder `.ipynb_checkpoints`.

**Comment by sanidhyas3s** [comment]
Done.

**Pull request merged**
