### PR TITLE
Assignment ML-0 Submission

### PR DESCRIPTION
**Pull request by PriyanshuPansari**
Final submission.

### CODE REVIEW

**Comment by DevPranjal** [comment]
Great work! Thanks.

@tushdon2 @aryanasura please review the submission.

**Comment by PriyanshuPansari** [comment]
@DevPranjal Is it correct or do I need to change something?

**Comment by DevPranjal** [comment]
Just a minor thing, could you please remove the folder `.ipynb_checkpoints`.

**Comment by PriyanshuPansari** [comment]
Removed

**Comment by aryanasura** [comment]
the submission is fine

**Pull request merged**
